### ISSUE TITLE
"Chrome Did Not Shut Down Correctly"

### ISSUE THREAD

**Issue by ScoopDL** [matt-cook/kiosk#245] opened 2017-06-28 22:01 UTC
Every 1-2 days I walk by my Kiosk display and the chromebox is off. When I restart it, it says that "Chrome did not shut down correctly."

I have the the device sleep mode disabled, but it seems that something is causing the software to crash.

**Comment by matt-cook** [comment] 2017-07-23 21:08
This appears to be a duplicate of https://github.com/matt-cook/kiosk/issues/247

**Closed by matt-cook** 2017-07-23 21:08 UTC
Labels: duplicate
