### ISSUE TITLE
Reset time entered is altered by an hour

### ISSUE THREAD

**Issue by matt-schuh** [matt-cook/kiosk#32] opened 2015-07-06 14:04 UTC
E.g. if I say to restart at 4pm (16:00) the program sets it to restart at 3pm (15:00)

**Comment by matt-cook** [comment] 2015-08-25 15:13
@matt-schuh do you know if this has been resolved?

**Comment by matt-schuh** [comment] 2015-08-25 15:36
Probably related to DST.  I think the code chops off an hour regardless of DST or not.

**Comment by matt-cook** [comment] 2017-04-13 19:39
probably a duplicate of: https://github.com/matt-cook/kiosk/issues/151

**Closed by matt-cook** 2017-04-13 19:39 UTC
Labels: bug
