### ISSUE TITLE
Printing does not work

### ISSUE THREAD

**Issue by sunnykoundal** [matt-cook/kiosk#152] opened 2016-11-25 04:39 UTC
I am using Kiosk app of chrome and printing is not working in that.
but on other hand if I manually create a kiosk in chrome by changing in property of chrome by adding 

> --kiosk --kiosk-printing --enable-print-preview "http://localhost:55573/"

into target under shortcut tab.

Its working fine for me.

Please let me know whats the reason why this same functionality is not working in kiosk?

Thanks in advance
Sunil Kumar

**Comment by lozal2244** [comment] 2016-12-01 11:42
interested :)

**Comment by matt-cook** [comment] 2016-12-01 19:07
@sunnykoundal thanks for the additional details. This is a duplicate of https://github.com/matt-cook/kiosk/issues/10 so we can continue the discussion there.

**Closed by matt-cook** 2016-12-01 19:07 UTC
Labels: duplicate
